import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar";

import { Roboto_Condensed } from "next/font/google";

const font = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TRIONN - Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-light  text-gray dark:bg-gray dark:text-light ${font.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
